apiVersion: v1
data:
  password: {{ .Values.primaryusersecretpassword | b64enc }}
  username: {{ .Values.primaryusersecretuser | b64enc }}
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install
  labels:
    pg-cluster: {{ .Values.pgclustername }}
    vendor: crunchydata
  name: {{ .Values.pgclustername }}-primaryuser-secret
  namespace: {{ .Values.namespace }}
type: Opaque
